### ISSUE TITLE
Fix configuration generation

### ISSUE THREAD

**Issue by wiebel** [hcshires/DSMRealTime#1]
I needed to use %20 notation to get the whitespaces handled correctly, quotes have been removed by the plugin.

**Comment by hcshires** [comment]
Hey there thanks for reporting your issue. Can you describe the bug exactly (i.e the lack of quotes) and attach your config file?

**Comment by hcshires** [comment]
I looked at the issue you're talking about and I realized the config.yml is being generated badly as a whole so I'll work on a fix for that. Should be released in less than a week.

**Comment by hcshires** [comment]
Unfortunately, Spigot does not support formatting and additional comments on the default config file, however the config should work without %20 notation. I updated my build anyway to support a header and save a little better. Hopefully you can find a fix to your issue in a different way and let me know if I can be of assistance.
